import { afterEach, describe, expect, it } from 'vitest'
import { mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { applyPlan } from './apply.js'
import { PlanBuilder } from './plan.js'
import { simulatePlan } from './simulate.js'
import type { ChangePlan, OutputLanguage } from './types.js'

/**
 * Language of the text `plan` and `apply` add to client files on their own: the
 * managed-file header and the block warning (F0-45).
 *
 * It comes from the plan, which carries the profile language, so both commands
 * write the same text and no caller can forget to pass it.
 */

const created: string[] = []

afterEach(async () => {
  await Promise.all(created.splice(0).map((dir) => rm(dir, { recursive: true, force: true })))
})

async function emptyRepo(): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), 'plumbward-language-'))
  created.push(root)
  return root
}

/** A managed file and a block, the two places that get text of their own. */
function planIn(language: OutputLanguage): ChangePlan {
  return new PlanBuilder(language)
    .add('test', [
      {
        kind: 'createFile',
        path: 'managed.yml',
        content: 'key: value\n',
        managed: true,
        reason: 'Managed file.',
      },
      {
        kind: 'ensureBlock',
        path: '.gitignore',
        blockId: 'test-block',
        content: 'dist/',
        commentStyle: 'hash',
        createIfMissing: true,
        reason: 'Managed block.',
      },
    ])
    .build()
}

/** One line of each text. Escaped so this file passes `scripts/english-only.mjs`. */
const EXPECTED: Record<OutputLanguage, readonly string[]> = {
  en: ['File generated by the Plumbward CLI.', 'Managed block. Do not edit inside the markers:'],
  es: [
    'Fichero generado por la CLI de gobernanza.',
    'Bloque gestionado autom\u00e1ticamente. No edites dentro de los marcadores:',
  ],
}

function expectLanguage(text: string, language: OutputLanguage): void {
  const other: OutputLanguage = language === 'en' ? 'es' : 'en'
  for (const line of EXPECTED[language]) expect(text).toContain(line)
  for (const line of EXPECTED[other]) expect(text).not.toContain(line)
}

describe('language of the text plan and apply add to client files', () => {
  for (const language of ['en', 'es'] as const) {
    it(`plan shows it in the plan language (${language})`, async () => {
      const simulation = await simulatePlan(planIn(language), {
        repoRoot: await emptyRepo(),
        version: '1.0.0',
      })
      expectLanguage(simulation.changes.map((change) => change.after).join('\n'), language)
    })

    it(`apply writes it in the plan language (${language})`, async () => {
      const root = await emptyRepo()
      await applyPlan(planIn(language), {
        repoRoot: root,
        version: '1.0.0',
        writtenOnBranch: null,
        writtenOnCommit: null,
        startedOnBranch: null,
        runCommands: false,
      })
      const written = await Promise.all(
        ['managed.yml', '.gitignore'].map((path) => readFile(join(root, path), 'utf8')),
      )
      expectLanguage(written.join('\n'), language)
    })
  }
})
