import { describe, expect, it } from 'vitest'
import { ensureBlock, readBlock, managedHeader, parseManagedHeader } from './blocks.js'

describe('ensureBlock', () => {
  const gitignore = 'node_modules/\ndist/\n'

  it('appends the block at the end without touching what came before', () => {
    const result = ensureBlock(gitignore, 'governance', '.governance/journal.json', 'hash', 'en')

    expect(result.changed).toBe(true)
    expect(result.replaced).toBe(false)
    expect(result.text.startsWith(gitignore)).toBe(true)
    expect(readBlock(result.text, 'governance', 'hash')).toContain('.governance/journal.json')
  })

  it('is idempotent', () => {
    const first = ensureBlock(gitignore, 'governance', 'content', 'hash', 'en')
    const second = ensureBlock(first.text, 'governance', 'content', 'hash', 'en')

    expect(second.changed).toBe(false)
    expect(second.text).toBe(first.text)
  })

  it('updates the content of the block without duplicating it', () => {
    const first = ensureBlock(gitignore, 'governance', 'version-1', 'hash', 'en')
    const second = ensureBlock(first.text, 'governance', 'version-2', 'hash', 'en')

    expect(second.replaced).toBe(true)
    expect(second.text).toContain('version-2')
    expect(second.text).not.toContain('version-1')
    expect(second.text.match(/plumbward:begin/g)).toHaveLength(1)
  })

  it('keeps intact whatever the client writes outside the markers', () => {
    const first = ensureBlock(gitignore, 'governance', 'a', 'hash', 'en')
    const edited = `${first.text}\n# the team's own rule\n*.local\n`
    const second = ensureBlock(edited, 'governance', 'b', 'hash', 'en')

    expect(second.text).toContain("# the team's own rule")
    expect(second.text).toContain('*.local')
    expect(second.text).toContain('node_modules/')
  })
})

describe('block warning', () => {
  it('is written in the profile language', () => {
    const english = ensureBlock('', 'governance', 'dist/', 'hash', 'en').text
    const spanish = ensureBlock('', 'governance', 'dist/', 'hash', 'es').text

    expect(english).toContain('# Managed block. Do not edit inside the markers:')
    expect(english).not.toContain('Bloque gestionado')
    // Escaped so this file passes scripts/english-only.mjs.
    expect(spanish).toContain('# Bloque gestionado autom\u00e1ticamente. No edites dentro de los marcadores:')
  })

  it('is replaced when the language changes, without duplicating the block', () => {
    const english = ensureBlock('', 'governance', 'dist/', 'hash', 'en').text
    const spanish = ensureBlock(english, 'governance', 'dist/', 'hash', 'es')

    expect(spanish.replaced).toBe(true)
    expect(spanish.text).not.toContain('Managed block')
    expect(spanish.text.match(/plumbward:begin/g)).toHaveLength(1)
  })
})

describe('managed header', () => {
  it('can be read back in either language', () => {
    for (const language of ['en', 'es'] as const) {
      const header = managedHeader('hash', '1.2.3', 'abc123def456', language)
      expect(parseManagedHeader(header)).toEqual({ version: '1.2.3', hash: 'abc123def456' })
    }
  })

  it('explains itself in the profile language', () => {
    expect(managedHeader('hash', '1.2.3', 'abc', 'en')).toContain('# File generated by the Plumbward CLI.')
    expect(managedHeader('hash', '1.2.3', 'abc', 'es')).toContain('# Fichero generado por la CLI de gobernanza.')
  })

  it('returns undefined for a file without a header', () => {
    expect(parseManagedHeader('plain content')).toBeUndefined()
  })
})
