/**
 * Managed blocks: the mechanism that makes `plumbward upgrade` possible without
 * destroying the client's work.
 *
 * Everything the tool injects into a file it does not own sits between
 * markers. An update only rewrites what is between the markers; a single line
 * outside them is never touched.
 */

export type CommentStyle = 'hash' | 'slash' | 'html' | 'semicolon'

/**
 * Language of the text written into client files: the block warning and the
 * managed-file header follow the profile, like the rest of what is generated.
 */
export type OutputLanguage = 'en' | 'es'

export const BEGIN_TOKEN = 'plumbward:begin'
export const END_TOKEN = 'plumbward:end'

interface Delimiters {
  readonly prefix: string
  readonly suffix: string
}

const DELIMITERS: Record<CommentStyle, Delimiters> = {
  hash: { prefix: '#', suffix: '' },
  slash: { prefix: '//', suffix: '' },
  semicolon: { prefix: ';', suffix: '' },
  html: { prefix: '<!--', suffix: ' -->' },
}

/** Wraps a text as a comment in the style of the target file. */
export function commentLine(style: CommentStyle, text: string): string {
  const { prefix, suffix } = DELIMITERS[style]
  return `${prefix} ${text}${suffix}`
}

function beginMarker(style: CommentStyle, blockId: string): string {
  return commentLine(style, `>>> ${BEGIN_TOKEN} ${blockId}`)
}

function endMarker(style: CommentStyle, blockId: string): string {
  return commentLine(style, `<<< ${END_TOKEN} ${blockId}`)
}

export interface EnsureBlockResult {
  readonly text: string
  readonly changed: boolean
  /** `true` if the block already existed and only its content was updated. */
  readonly replaced: boolean
}

/**
 * Inserts the block if it does not exist, or replaces its content if it is
 * already there.
 *
 * Idempotent: if the content matches what is already there, the file is not
 * touched.
 */
export function ensureBlock(
  original: string,
  blockId: string,
  content: string,
  style: CommentStyle,
  language: OutputLanguage,
): EnsureBlockResult {
  const begin = beginMarker(style, blockId)
  const end = endMarker(style, blockId)
  const warning = blockWarning(language).map((line) => commentLine(style, line))

  const body = [begin, ...warning, content.trimEnd(), end].join('\n')

  const beginIndex = original.indexOf(begin)
  const endIndex = original.indexOf(end)

  if (beginIndex !== -1 && endIndex !== -1 && endIndex > beginIndex) {
    const before = original.slice(0, beginIndex)
    const after = original.slice(endIndex + end.length)
    const next = `${before}${body}${after}`
    return { text: next, changed: next !== original, replaced: true }
  }

  const separator = original.length === 0 ? '' : original.endsWith('\n') ? '\n' : '\n\n'
  const next = `${original}${separator}${body}\n`
  return { text: next, changed: true, replaced: false }
}

function blockWarning(language: OutputLanguage): string[] {
  return language === 'es'
    ? [
        'Bloque gestionado automáticamente. No edites dentro de los marcadores:',
        '`plumbward upgrade` regenerará su contenido.',
      ]
    : [
        'Managed block. Do not edit inside the markers:',
        '`plumbward upgrade` will regenerate its content.',
      ]
}

/** Extracts the current content of a managed block, if it exists. */
export function readBlock(
  original: string,
  blockId: string,
  style: CommentStyle,
): string | undefined {
  const begin = beginMarker(style, blockId)
  const end = endMarker(style, blockId)
  const beginIndex = original.indexOf(begin)
  const endIndex = original.indexOf(end)
  if (beginIndex === -1 || endIndex === -1 || endIndex <= beginIndex) return undefined
  return original.slice(beginIndex + begin.length, endIndex).trim()
}

/**
 * Header of a fully managed file. The hash lets `upgrade` detect whether the
 * client edited the file by hand and, in that case, not overwrite it.
 */
export function managedHeader(
  style: CommentStyle,
  version: string,
  contentHash: string,
  language: OutputLanguage,
): string {
  const explanation =
    language === 'es'
      ? [
          'Fichero generado por la CLI de gobernanza.',
          'Si lo editas a mano, `plumbward upgrade` dejará de actualizarlo',
          'y te avisará del conflicto en lugar de sobrescribir tus cambios.',
        ]
      : [
          'File generated by the Plumbward CLI.',
          'If you edit it by hand, `plumbward upgrade` will stop updating it',
          'and will warn you about the conflict instead of overwriting your changes.',
        ]
  return [
    commentLine(style, `plumbward:managed v=${version} hash=${contentHash}`),
    ...explanation.map((line) => commentLine(style, line)),
  ].join('\n')
}

/** Reads the managed header of a file, if it has one. */
export function parseManagedHeader(
  text: string,
): { version: string; hash: string } | undefined {
  const match = /plumbward:managed v=([^\s]+) hash=([0-9a-f]+)/.exec(text)
  if (!match?.[1] || !match[2]) return undefined
  return { version: match[1], hash: match[2] }
}
