import { parseYamlToJson } from '@plumbward/ast'
import { readFileIfExists, resolveInRepo } from '@plumbward/core'
import type { HealthCheck, RepoContext } from '@plumbward/packs-sdk'

/**
 * Checks that read the workflows **as they are in the repository**.
 *
 * `apply` does not overwrite existing files, so a workflow generated by an
 * earlier version can keep doing what the current configuration no longer
 * says: deploying from a branch nobody chose, or reviewing only the PRs to one
 * branch. Looking at the configuration is not enough; the file has to be read.
 *
 * When in doubt, they warn: a workflow that cannot be interpreted is treated as
 * suspicious (ADR 0005: fail towards more protection).
 */

const PROD_WORKFLOW = '.github/workflows/ci-prod.yml'
const DEV_WORKFLOW = '.github/workflows/ci-dev.yml'

/**
 * Branches of a trigger: a list if it filters by branch, `null` if it fires on
 * all of them, `undefined` if the trigger does not exist or the file cannot be
 * understood.
 */
export function triggerBranches(text: string, event: 'push' | 'pull_request'): string[] | null | undefined {
  let doc: unknown
  try {
    doc = parseYamlToJson(text)
  } catch {
    return undefined
  }
  if (typeof doc !== 'object' || doc === null) return undefined
  // In YAML 1.1 the `on` key can be read as the boolean `true`.
  const record = doc as Record<string, unknown>
  const on = record['on'] ?? record['true']
  if (typeof on !== 'object' || on === null || !(event in on)) return undefined
  const trigger = (on as Record<string, unknown>)[event]
  if (trigger === null || typeof trigger !== 'object') return null
  const branches = (trigger as Record<string, unknown>)['branches']
  if (branches === undefined) return null
  if (!Array.isArray(branches) || !branches.every((b) => typeof b === 'string')) return undefined
  return branches as string[]
}

async function read(context: RepoContext, path: string): Promise<string | undefined> {
  return readFileIfExists(resolveInRepo(context.scan.repoRoot, path))
}

async function releaseCheck(context: RepoContext): Promise<HealthCheck | undefined> {
  const { deployTarget, branches } = context.profile
  const release = branches.release
  const prodText = await read(context, PROD_WORKFLOW)
  if (deployTarget === 'none' && prodText === undefined) return undefined

  const base = { id: 'release-branch', label: 'Release branch configured' }
  const configureHint =
    'Set the branch that deploys in `.governance/config.yml` (`branches.release`). Plumbward does not infer it: deploying from a guessed branch cannot be undone.'

  if (prodText === undefined) {
    return release !== null
      ? { ...base, ok: true, detail: `Will deploy to production from "${release}".` }
      : {
          ...base,
          ok: false,
          detail: `There is a deploy target (${deployTarget}) but no release branch: the production workflow was not generated.`,
          fixHint: configureHint,
        }
  }

  const deploysFrom = triggerBranches(prodText, 'push')
  const fileHint = `Check which branch ${PROD_WORKFLOW} deploys from and that it matches \`branches.release\`, or delete the workflow.`
  if (release === null) {
    return {
      ...base,
      ok: false,
      detail: `${PROD_WORKFLOW} exists but no release branch is configured: it may be deploying from a branch nobody chose.`,
      fixHint: fileHint,
    }
  }
  if (deploysFrom === undefined) {
    return { ...base, ok: false, detail: `Cannot determine which branch ${PROD_WORKFLOW} deploys from.`, fixHint: fileHint }
  }
  if (deploysFrom === null) {
    return { ...base, ok: false, detail: `${PROD_WORKFLOW} deploys on a push to any branch.`, fixHint: fileHint }
  }
  if (deploysFrom.length !== 1 || deploysFrom[0] !== release) {
    return {
      ...base,
      ok: false,
      detail: `${PROD_WORKFLOW} deploys from [${deploysFrom.join(', ')}], but the configured release branch is "${release}".`,
      fixHint: fileHint,
    }
  }
  return { ...base, ok: true, detail: `Deploys to production from "${release}".` }
}

async function pullRequestCoverageCheck(context: RepoContext): Promise<HealthCheck | undefined> {
  const devText = await read(context, DEV_WORKFLOW)
  if (devText === undefined) return undefined
  const base = { id: 'pr-coverage', label: 'Every Pull Request goes through CI' }
  const hint = `Remove the branch filter from \`pull_request\` in ${DEV_WORKFLOW}: CI must review every PR.`
  const filter = triggerBranches(devText, 'pull_request')
  if (filter === null) return { ...base, ok: true, detail: 'Every Pull Request is reviewed.' }
  if (filter === undefined) {
    return { ...base, ok: false, detail: `Cannot verify which Pull Requests ${DEV_WORKFLOW} applies to.`, fixHint: hint }
  }
  return {
    ...base,
    ok: false,
    detail: `Only PRs targeting [${filter.join(', ')}] are reviewed; the rest do not go through CI.`,
    fixHint: hint,
  }
}

export async function workflowChecks(context: RepoContext): Promise<HealthCheck[]> {
  const checks = await Promise.all([releaseCheck(context), pullRequestCoverageCheck(context)])
  return checks.filter((check): check is HealthCheck => check !== undefined)
}
